# Generated by Django 5.2.7 on 2025-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokeninfo",
            name="is_processing",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag indicating if this token is currently being analyzed",
            ),
        ),
    ]
